### ISSUE TITLE
Hangs when opening a (malformed?) xm file

### ISSUE THREAD

**Issue by aklapper** [milkytracker/MilkyTracker#132]
```
$:a\> rpm -q milkytracker
milkytracker-0.90.86-5.fc26.x86_64
$:a\> gdb milkytracker 
GNU gdb (GDB) Fedora 8.0.1-26.fc26
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from milkytracker...Reading symbols from /usr/lib/debug/usr/bin/milkytracker.debug...done.
done.
(gdb) run
Starting program: /usr/bin/milkytracker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff5caf700 (LWP 18433)]
[New Thread 0x7fffe5b85700 (LWP 18434)]
[Thread 0x7fffe5b85700 (LWP 18434) exited]
[New Thread 0x7fffe5b85700 (LWP 18435)]
SDL: Using audio driver: pulse
SDL: Buffer size = 1024 samples (requested 2048)
[New Thread 0x7fffe5384700 (LWP 18436)]
^C
Thread 1 "milkytracker" received signal SIGINT, Interrupt.
PatternTools::getHexNumDigits (value=4294967295) at PatternTools.cpp:682
682		while (value >> i*4)
(gdb) thread apply all bt full

Thread 5 (Thread 0x7fffe5384700 (LWP 18436)):
#0  0x00007ffff646cacd in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff7418231 in poll (__timeout=-1, __nfds=2, __fds=0x7fffe5383e30) at /usr/include/bits/poll2.h:46
No locals.
#2  alsaMidiHandler (ptr=0x555555a551b0) at RtMidi.cpp:1175
        apiData = 0x555555b7e8a0
        nBytes = <optimized out>
        time = <optimized out>
        lastTime = <optimized out>
        continueSysex = false
        message = {bytes = std::vector of length 0, capacity 0, timeStamp = 0}
        poll_fd_count = 2
        poll_fds = 0x7fffe5383e30
        ev = 0x0
        result = <optimized out>
        buffer = 0x7fffe0009530 " \231"
#3  0x00007ffff792236d in start_thread (arg=0x7fffe5384700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fffe5384700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737039058688, 6861193870850429706, 0, 140737488344784, 140737039059392, 0, -6861215300587580662, -6861176456496508150}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007ffff6478bbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

Thread 4 (Thread 0x7fffe5b85700 (LWP 18435)):
#0  0x00007ffff646cba6 in __GI_ppoll (fds=0x555555b91c60, nfds=3, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
        resultvar = 18446744073709551102
        sc_cancel_oldtype = 2
        tval = {tv_sec = 4294967295, tv_nsec = 140737172979998}
#1  0x00007fffed33c5b1 in ppoll (__ss=0x0, __timeout=<optimized out>, __nfds=<optimized out>, __fds=<optimized out>) at /usr/include/bits/poll2.h:77
No locals.
#2  pa_mainloop_poll (m=m@entry=0x555555b8b8d0) at pulse/mainloop.c:852
        ts = {tv_sec = 93824998750416, tv_nsec = 93824998750848}
        __func__ = "pa_mainloop_poll"
        __PRETTY_FUNCTION__ = "pa_mainloop_poll"
#3  0x00007fffed33cbc0 in pa_mainloop_iterate (m=0x555555b8b8d0, block=<optimized out>, retval=0x0) at pulse/mainloop.c:926
        r = 0
#4  0x00007ffff7b6e38d in PULSE_WaitAudio (this=0x555555b8ba80) at src/audio/pulse/SDL_pulseaudio.c:310
        size = <optimized out>
#5  0x00007ffff7b4211c in SDL_RunAudio (audiop=audiop@entry=0x555555b8ba80) at src/audio/SDL_audio.c:222
        audio = 0x555555b8ba80
        stream = 0x555555b92000 ""
        stream_len = 4096
---Type <return> to continue, or q <return> to quit---
        udata = 0x555555a4e5e0
        fill = 0x555555631280 <AudioDriver_SDL::fill_audio(void*, unsigned char*, int)>
        silence = 0
#6  0x00007ffff7b4a7b8 in SDL_RunThread (data=0x555555b96590) at src/thread/SDL_thread.c:204
        args = 0x555555b96590
        userfunc = 0x7ffff7b42080 <SDL_RunAudio>
        userdata = 0x555555b8ba80
        statusloc = 0x555555b97be0
#7  0x00007ffff7b8cdb9 in RunThread (data=<optimized out>) at src/thread/pthread/SDL_systhread.c:47
No locals.
#8  0x00007ffff792236d in start_thread (arg=0x7fffe5b85700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fffe5b85700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737047451392, 6861193870850429706, 0, 140737488344832, 93824998776480, 20, -6861216398488595702, -6861176456496508150}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#9  0x00007ffff6478bbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

Thread 2 (Thread 0x7ffff5caf700 (LWP 18433)):
#0  0x00007ffff792c92d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff7b8f425 in SDL_Delay (ms=ms@entry=1) at src/timer/unix/SDL_systimer.c:118
        was_error = <optimized out>
        elapsed = {tv_sec = 0, tv_nsec = 749555}
        tv = {tv_sec = 0, tv_nsec = 1000000}
#2  0x00007ffff7b8f472 in RunTimer (unused=unused@entry=0x0) at src/timer/unix/SDL_systimer.c:203
No locals.
#3  0x00007ffff7b4a7b8 in SDL_RunThread (data=0x555555a07d70) at src/thread/SDL_thread.c:204
        args = 0x555555a07d70
        userfunc = 0x7ffff7b8f450 <RunTimer>
        userdata = 0x0
        statusloc = 0x555555a07a50
#4  0x00007ffff7b8cdb9 in RunThread (data=<optimized out>) at src/thread/pthread/SDL_systhread.c:47
No locals.
#5  0x00007ffff792236d in start_thread (arg=0x7ffff5caf700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7ffff5caf700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737317107456, 6861193870850429706, 0, 140737488345200, 140737317108160, 0, -6861180238085188854, -6861176456496508150}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff6478bbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

Thread 1 (Thread 0x7ffff7fcf440 (LWP 18429)):
#0  PatternTools::getHexNumDigits (value=4294967295) at PatternTools.cpp:682
        i = 561624200
#1  0x0000555555585089 in PatternEditorControl::getRowCountWidth (this=<optimized out>) at PatternEditorControl.cpp:866
No locals.
#2  0x00005555555850d1 in PatternEditorControl::adjustExtents (this=this@entry=0x555555b66f60) at PatternEditorControl.cpp:881
No locals.
#3  0x0000555555587061 in PatternEditorControl::paint (this=0x555555b66f60, g=0x555555a9b810) at PatternEditorControl.cpp:241
        lineColor = {r = 96, g = 32, b = 64}
        bColor = {r = 85, g = 127, b = 170}
        dColor = {r = 32, g = 48, b = 64}
        bCursor = {r = 127, g = 42, b = 85}
        dCursor = {r = 48, g = 16, b = 32}
        name = "`o\266UUU\000\000\330UXUUU\000\000\000\000\000\000\000\000\000\000`o\266UUU\000"
        i = <optimized out>
        j = <optimized out>
        selectionStart = <optimized out>
        selectionEnd = <optimized out>
        fontCharWidth3x = <optimized out>
        fontCharWidth2x = <optimized out>
        fontCharWidth1x = <optimized out>
        patternTools = <optimized out>
        startx = <optimized out>
        previousPatternIndex = <optimized out>
        previousRowIndex = <optimized out>
        nextPatternIndex = <optimized out>
        nextRowIndex = <optimized out>
        songPosOrderListIndex = <optimized out>
        pattern = <optimized out>
        noteColor = <optimized out>
        insColor = <optimized out>
        volColor = <optimized out>
        effColor = <optimized out>
        opColor = <optimized out>
        hiLightPrimary = <optimized out>
        hiLightSecondary = <optimized out>
        hiLightPrimaryRow = <optimized out>
        hiLightSecondaryRow = <optimized out>
        textColor = <optimized out>
        numVisibleChannels = <optimized out>
        px = <optimized out>
#4  0x0000555555668d5d in PPScreen::paintControl (this=0x555555a9b890, control=0x555555b66f60, update=<optimized out>) at Screen.cpp:418
        g = 0x555555a9b810
        paintContextMenus = <optimized out>
#5  0x00005555556013e5 in Tracker::updatePatternEditorControl (this=this@entry=0x555555a40910, repaint=<optimized out>, fast=fast@entry=false) at TrackerUpdate.cpp:511
No locals.
#6  0x00005555555e1fcf in Tracker::setNumChannels (this=this@entry=0x555555a40910, numChannels=<optimized out>, repaint=repaint@entry=false) at Tracker.cpp:360
No locals.
---Type <return> to continue, or q <return> to quit---
#7  0x0000555555601dba in Tracker::updateSongInfo (this=this@entry=0x555555a40910, repaint=repaint@entry=false) at TrackerUpdate.cpp:554
No locals.
#8  0x00005555556027be in Tracker::updateAfterLoad (this=this@entry=0x555555a40910, loadResult=<optimized out>, wasPlaying=<optimized out>, wasPlayingPattern=<optimized out>) at TrackerUpdate.cpp:992
        __PRETTY_FUNCTION__ = "void Tracker::updateAfterLoad(bool, bool, bool)"
#9  0x00005555555e6f34 in Tracker::loadTypeFromFile (this=this@entry=0x555555a40910, eType=eType@entry=..., fileName=..., suspendPlayer=suspendPlayer@entry=true, repaint=repaint@entry=true, 
    saveCheck=saveCheck@entry=false) at Tracker.cpp:2699
        res = <optimized out>
#10 0x00005555555e7741 in Tracker::loadTypeWithDialog (this=0x555555a40910, eLoadType=..., suspendPlayer=suspendPlayer@entry=true, repaint=repaint@entry=true) at Tracker.cpp:2845
        fileName = {strBuffer = 0x555555b7d6a0 "/home/acko/wav/xm/FLIPSQU1.XM", allocatedSize = 30}
        fileExtProvider = {static moduleExtensions = 0x5555559d0120 <FileExtProvider::moduleExtensions>, static instrumentExtensions = <same as static member of an already seen type>, 
          static sampleExtensions = <same as static member of an already seen type>, static patternExtensions = <same as static member of an already seen type>, 
          static trackExtensions = <same as static member of an already seen type>, static colorExtensions = <same as static member of an already seen type>, tempList = 0x555555bad9d0, tempExtensions = {
            numValuesAllocated = 64, values = 0x555555bacca0, numValues = 64, destroy = true}}
        openPanel = 0x555555a55f20
        res = true
#11 0x00005555555e7978 in Tracker::loadType (this=<optimized out>, eType=..., eType@entry=...) at Tracker.cpp:2867
No locals.
#12 0x00005555555f3ada in Tracker::eventKeyDownBinding_Open (this=<optimized out>) at TrackerKeyboard.cpp:496
        this = <optimized out>
#13 0x00005555555e9671 in Tracker::handleEvent (this=0x555555a40910, sender=0x555555b60b40, event=<optimized out>) at Tracker.cpp:786
        buffer = "\000\244\241UUU\000\000kx\365\364\377\177\000\000ض\241UUU\000\000\000@\f%\r\316\301\244P\266\241UUU\000\000\000\244\241UUU\000\000\260\210\272UUU\000\000\000\365\267UUU\000\000\320\322\377\377\377\177\000\000\004-\033\365\377\177\000\000\000\365\267UUU\000\000F:\033\365\377\177\000\000 \323\377\377"
        __PRETTY_FUNCTION__ = "virtual pp_int32 Tracker::handleEvent(PPObject*, PPEvent*)"
#14 0x00005555556509ab in PPButton::handleButtonRelease (this=<optimized out>, postEvent=<optimized out>, event=<optimized out>, rMouseDown=<optimized out>, lMouseDown=<optimized out>) at Button.cpp:302
        e = {<PPObject> = {<No data fields>}, ID = eCommand, 
          userData = "UU\000\000]\362\032\365\377\177\000\000\001\001\204\024\000\000\000\000\003\000 \003", '\000' <repeats 29 times>, "@\f%\r\316\301\244\340\231\250UUU\000\000\340\231\250UUU\000\000\340\323\377\377\377\177\000\000ZW\266\367\377\177\000\000Q\000B\000O\000\r\000\000@\f%\r\316\301\244\371\373fUUU\000\000\231\370fUUU\000\000Q\000\000\000B\000\000\000\240\000\000\000O\000\000\000Q\000\000\000B\000\000\000\240\000\000\000O", '\000' <repeats 12 times>, "@\f%\r\316\301\244\020\270\251UUU\000\000O\000\000\000\000\000\000\000\220\270\251UUU\000\000\272\213fUUU"..., dataSize = 0, metaData = 0}
#15 0x00005555556517e1 in PPButton::dispatchEvent (this=0x555555b60b40, event=0x7fffffffda00) at Button.cpp:236
No locals.
#16 0x0000555555652e9c in PPContainer::dispatchEvent (this=0x555555b607f0, event=0x7fffffffda00) at Container.cpp:111
        control = 0x555555b60b40
        i = <optimized out>
        res = 0
        handleEvent = false
#17 0x0000555555652e9c in PPContainer::dispatchEvent (this=0x555555a9bac0, event=0x7fffffffda00) at Container.cpp:111
        control = 0x555555b607f0
        i = <optimized out>
        res = 0
        handleEvent = false
#18 0x00005555556696e5 in PPScreen::raiseEvent (this=0x555555a9b890, event=0x7fffffffda00) at Screen.cpp:227
No locals.
#19 0x0000555555603ddf in RaiseEventSerialized (event=0x7fffffffda00) at sdl/SDL_Main.cpp:148
No locals.
#20 0x0000555555604636 in RaiseEventSerialized (event=0x7fffffffda00) at sdl/SDL_Main.cpp:145
No locals.
#21 translateMouseUpEvent (mouseButton=1, localMouseX=<optimized out>, localMouseY=<optimized out>) at sdl/SDL_Main.cpp:522
        myEvent = {<PPObject> = {<No data fields>}, ID = eLMouseUp, 
          userData = "\177\000\000\000I\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\271\030\267\367\377\177", '\000' <repeats 122 times>, "nӸ\367\377\177\000\000\000\000\000\000\000\000\000\000\254w\264\367\377\177\000\000\001\000\000\000\000\000\000\000\360\244\240UUU\000\000\001\000\000\000\000\000\000\000\000@\f%\r"..., dataSize = 8, metaData = 0}
#22 0x0000555555568df8 in main (argc=<optimized out>, argv=<optimized out>) at sdl/SDL_Main.cpp:1121
---Type <return> to continue, or q <return> to quit---
        oldCwd = {strBuffer = 0x555555a079e0 "/home/acko/", allocatedSize = 12}
        event = {type = 6 '\006', active = {type = 6 '\006', gain = 0 '\000', state = 1 '\001'}, key = {type = 6 '\006', which = 0 '\000', state = 1 '\001', keysym = {scancode = 127 '\177', sym = SDLK_UNKNOWN, 
              mod = KMOD_NONE, unicode = 0}}, motion = {type = 6 '\006', which = 0 '\000', state = 1 '\001', x = 127, y = 73, xrel = 0, yrel = 0}, button = {type = 6 '\006', which = 0 '\000', 
            button = 1 '\001', state = 0 '\000', x = 127, y = 73}, jaxis = {type = 6 '\006', which = 0 '\000', axis = 1 '\001', value = 127}, jball = {type = 6 '\006', which = 0 '\000', ball = 1 '\001', 
            xrel = 127, yrel = 73}, jhat = {type = 6 '\006', which = 0 '\000', hat = 1 '\001', value = 0 '\000'}, jbutton = {type = 6 '\006', which = 0 '\000', button = 1 '\001', state = 0 '\000'}, resize = {
            type = 6 '\006', w = 4784255, h = 0}, expose = {type = 6 '\006'}, quit = {type = 6 '\006'}, user = {type = 6 '\006', code = 4784255, data1 = 0x0, data2 = 0x0}, syswm = {type = 6 '\006', msg = 0x0}}
        loadFile = <optimized out>
        defaultBPP = <optimized out>
        orientation = <optimized out>
        swapRedBlue = <optimized out>
        fullScreen = <optimized out>
        noSplash = <optimized out>
        recVelocity = <optimized out>
        path = {<PPPath> = {_vptr.PPPath = 0x5555559cb6e0 <vtable for PPPath_POSIX+16>}, dir = 0x7ffff7de6503 <_dl_fixup+211>, current = {strBuffer = 0x555555a079a0 "/home/acko/", allocatedSize = 12}, 
          entry = {<PPPathEntry> = {_vptr.PPPathEntry = 0x5555559cb670 <vtable for PPPathEntry_POSIX+16>, name = {strBuffer = 0x555555a079c0 "", allocatedSize = 8}, type = 9, size = 32767}, <No data fields>}}
(gdb) list
677	{
678		if (value == 0)
679			return 1;
680	
681		pp_uint32 i = 0;
682		while (value >> i*4)
683			i++;
684	
685		return i;
686	}
(gdb) info register
rax            0x2179b488	561624200
rbx            0x8	8
rcx            0x85e6d21c	2246496796
rdx            0xf	15
rsi            0x555555a99c40	93824997760064
rdi            0xffffffff	4294967295
rbp            0x280	0x280
rsp            0x7fffffffcd78	0x7fffffffcd78
r8             0x1d6	470
r9             0x1d6	470
r10            0x26c	620
r11            0x0	0
r12            0x555555a9b890	93824997767312
r13            0x555555a9b810	93824997767184
r14            0x0	0
r15            0x555555b66f60	93824998600544
rip            0x555555594ae3	0x555555594ae3 <PatternTools::getHexNumDigits(unsigned int)+19>
eflags         0x206	[ PF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) 
```

**Comment by jcowgill** [comment]
Could you upload the XM file somewhere?

Having said that, there is an obvious bug in this loop:
```cpp
pp_uint32 i = 0;
while (value >> i*4)
    i++;
```

If `value` starts at `0xFFFFFFFF`, the loop will continue until `i` is `8`. At this point it will try to evaluate `value >> 32` which will invoke undefined behavior.

**Comment by aklapper** [comment]
[xm.zip](https://github.com/milkytracker/MilkyTracker/files/1318086/xm.zip)

**Comment by aklapper** [comment]
I'm pretty sure it's a malformed file as it's from an old backup CD that could not be read as expected, however I'd expect applications to not crash, no matter what. :)
