### ISSUE TITLE
Immediately crashes when starting with -orientation command line parameter

### ISSUE THREAD

**Issue by aklapper** [milkytracker/MilkyTracker#138]
Running on Fedora 26 under GNOME / Wayland:

```
$:acko\> milkytracker --help
Usage: milkytracker [-bpp N] [-swap] [-orientation NORMAL|ROTATE90CCW|ROTATE90CW] [-fullscreen] [-nosplash] [-nonstdkb] [-recvelocity]
$:acko\> rpm -q milkytracker
milkytracker-0.90.86-5.fc26.x86_64
$:acko\> gdb milkytracker
GNU gdb (GDB) Fedora 8.0.1-26.fc26
Reading symbols from milkytracker...Reading symbols from /usr/lib/debug/usr/bin/milkytracker.debug...done.
done.
(gdb) run -orientation ROTATE90CW
Starting program: /usr/bin/milkytracker -orientation ROTATE90CW
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff5caf700 (LWP 12972)]

Thread 1 "milkytracker" received signal SIGSEGV, Segmentation fault.
PPDisplayDeviceFB::swap (this=0x555555a9a520, r2=...) at sdl/DisplayDeviceFB_SDL.cpp:631
631									*(dstPtr+=(dstPitch>>2)) = *srcPtr++;
(gdb) thread apply all bt full

Thread 2 (Thread 0x7ffff5caf700 (LWP 12972)):
#0  0x00007ffff792c92d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff7b8f635 in SDL_Delay (ms=ms@entry=1) at src/timer/unix/SDL_systimer.c:118
        was_error = <optimized out>
        elapsed = {tv_sec = 0, tv_nsec = 915322}
        tv = {tv_sec = 0, tv_nsec = 1000000}
#2  0x00007ffff7b8f682 in RunTimer (unused=unused@entry=0x0) at src/timer/unix/SDL_systimer.c:203
No locals.
#3  0x00007ffff7b4a758 in SDL_RunThread (data=0x555555a07d70) at src/thread/SDL_thread.c:204
        args = 0x555555a07d70
        userfunc = 0x7ffff7b8f660 <RunTimer>
        userdata = 0x0
        statusloc = 0x555555a07a50
#4  0x00007ffff7b8cfb9 in RunThread (data=<optimized out>) at src/thread/pthread/SDL_systhread.c:47
No locals.
#5  0x00007ffff792236d in start_thread (arg=0x7ffff5caf700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7ffff5caf700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737317107456, -4013184266627557465, 0, 140737488345152, 140737317108160, 0, 4013170960295942055, 
                4013165800291194791}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff6478bbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

Thread 1 (Thread 0x7ffff7fcf440 (LWP 12971)):
#0  PPDisplayDeviceFB::swap (this=0x555555a9a520, r2=...) at sdl/DisplayDeviceFB_SDL.cpp:631
        x = <optimized out>
        srcPtr = 0x7fffed641014
        dstPtr = 0x8000f7e4f77c
        y = 0
        srcPitch = <optimized out>
        dst = 0x7ffff7e4f000 ""
        srcBPP = 4
        dstPitch = 1920
        src = 0x7fffed641010 ""
        dstBPP = 4
        r = {x1 = 0, y1 = <optimized out>, x2 = <optimized out>, y2 = 480}
#1  0x000055555566f78d in PPDisplayDeviceFB::update (this=0x555555a9a520) at sdl/DisplayDeviceFB_SDL.cpp:162
        r = {x1 = 0, y1 = 0, x2 = 640, y2 = 480}
        this = 0x555555a9a520
#2  0x00005555555ff829 in Tracker::showSplash (this=this@entry=0x555555a40910) at TrackerStartUp.cpp:117
        shade = <optimized out>
        deltaT = <optimized out>
#3  0x000055555560025b in Tracker::startUp (this=0x555555a40910, forceNoSplash=false) at TrackerStartUp.cpp:179
        noSplash = 254
        startTime = 112
        dTime = <optimized out>
        masterStart = <optimized out>
#4  0x0000555555605102 in initTracker (bpp=4294967295, orientation=PPDisplayDevice::ORIENTATION_ROTATE90CW, swapRedBlue=<optimized out>, fullScreen=<optimized out>, noSplash=<optimized out>)
    at sdl/SDL_Main.cpp:932
        act = {__sigaction_handler = {sa_handler = 0x555555603f20 <crashHandler(int)>, sa_sigaction = 0x555555603f20 <crashHandler(int)>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = -2147483648, 
          sa_restorer = 0x0}
        oldAct = {__sigaction_handler = {sa_handler = 0x7ffff7b41e50 <SDL_Parachute>, sa_sigaction = 0x7ffff7b41e50 <SDL_Parachute>}, sa_mask = {__val = {0, 93824997172464, 2048, 93824997391520, 0, 4294967296, 
              140733193388032, 0, 2160316178846629888, 0, 140737488345840, 140737488345888, 4294967295, 3, 140737349162762, 0}}, sa_flags = 67108864, sa_restorer = 0x7ffff792d3b0 <__restore_rt>}
        info = {version = {major = 1 '\001', minor = 2 '\002', patch = 15 '\017'}, subsystem = SDL_SYSWM_X11, info = {x11 = {display = 0x555555a0abb0, window = 0, lock_func = 0x7ffff7b7a280 <lock_display>, 
              unlock_func = 0x7ffff7b7a290 <unlock_display>, fswindow = 35651586, wmwindow = 35651587, gfxdisplay = 0x555555a1a400}}}
        windowSize = <optimized out>
        scaleFactor = 1
#5  0x0000555555568d10 in main (argc=<optimized out>, argv=<optimized out>) at sdl/SDL_Main.cpp:1069
        oldCwd = {strBuffer = 0x555555a079e0 "/home/acko/", allocatedSize = 12}
        event = {type = 232 '\350', active = {type = 232 '\350', gain = 221 '\335', state = 255 '\377'}, key = {type = 232 '\350', which = 221 '\335', state = 255 '\377', keysym = {scancode = 255 '\377', 
              sym = 4294958600, mod = (KMOD_LSHIFT | KMOD_RSHIFT | KMOD_LCTRL | KMOD_RCTRL | KMOD_LALT | KMOD_RALT | KMOD_LMETA | KMOD_RMETA | KMOD_NUM | KMOD_CAPS | KMOD_MODE | unknown: 60), unicode = 3328}}, 
          motion = {type = 232 '\350', which = 221 '\335', state = 255 '\377', x = 32767, y = 0, xrel = -8696, yrel = -1}, button = {type = 232 '\350', which = 221 '\335', button = 255 '\377', 
            state = 255 '\377', x = 32767, y = 0}, jaxis = {type = 232 '\350', which = 221 '\335', axis = 255 '\377', value = 32767}, jball = {type = 232 '\350', which = 221 '\335', ball = 255 '\377', 
            xrel = 32767, yrel = 0}, jhat = {type = 232 '\350', which = 221 '\335', hat = 255 '\377', value = 255 '\377'}, jbutton = {type = 232 '\350', which = 221 '\335', button = 255 '\377', 
            state = 255 '\377'}, resize = {type = 232 '\350', w = 32767, h = -8696}, expose = {type = 232 '\350'}, quit = {type = 232 '\350'}, user = {type = 232 '\350', code = 32767, data1 = 0x7fffffffde08, 
            data2 = 0x5555559d0d00 <TrackerConfig::stringButtonPlus>}, syswm = {type = 232 '\350', msg = 0x7fffffffde08}}
        loadFile = <optimized out>
        defaultBPP = <optimized out>
        orientation = <optimized out>
        swapRedBlue = <optimized out>
        fullScreen = <optimized out>
        noSplash = <optimized out>
        recVelocity = <optimized out>
        path = {<PPPath> = {_vptr.PPPath = 0x5555559cb6e0 <vtable for PPPath_POSIX+16>}, dir = 0x7ffff7de6503 <_dl_fixup+211>, current = {strBuffer = 0x555555a079a0 "/home/acko/", allocatedSize = 12}, 
          entry = {<PPPathEntry> = {_vptr.PPPathEntry = 0x5555559cb670 <vtable for PPPathEntry_POSIX+16>, name = {strBuffer = 0x555555a079c0 "", allocatedSize = 8}, type = 9, size = 32767}, <No data fields>}}
(gdb) info register
rax            0x7fffed641014	140737176145940
rbx            0x0	0
rcx            0x8000f7e4f77c	140741647333244
rdx            0x0	0
rsi            0x780	1920
rdi            0x7fffed641a10	140737176148496
rbp            0x555555a9a520	0x555555a9a520
rsp            0x7fffffffd7a0	0x7fffffffd7a0
r8             0x0	0
r9             0xa00	2560
r10            0x0	0
r11            0xfffff880	4294965376
r12            0x1e0	480
r13            0x0	0
r14            0x7fffed641010	140737176145936
r15            0xa00	2560
rip            0x55555566f34d	0x55555566f34d <PPDisplayDeviceFB::swap(PPRect const&)+2845>
eflags         0x10216	[ PF AF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) list
626							for (pp_uint32 y = r.y1; y < r.y2; y++)
627							{
628								pp_uint32* srcPtr = (pp_uint32*)(src + y*srcPitch + r.x1*srcBPP);
629								pp_uint32* dstPtr = (pp_uint32*)(dst + (realWidth-1-y)*dstBPP + (dstPitch*(r.x1-1)));
630								for (pp_uint32 x = r.x1; x < r.x2; x++)
631									*(dstPtr+=(dstPitch>>2)) = *srcPtr++;
632							}
633						}
634						
635						break;
(gdb) 
```

**Comment by noxarivis** [comment]
isnt your version a bit old?

**Comment by aklapper** [comment]
My version is what is packaged in Fedora 26. So far I've been too lazy to compile it myself.

**Comment by noxarivis** [comment]
its very easy, just get sdl2 headers and a c++ compiler,
thats it.
