### ISSUE TITLE
'cln' crash.

### ISSUE THREAD

**Issue by FaZz321** [milkytracker/MilkyTracker#350]
Noticed that pushing "cln" button causes a crash with 'signal 11' in one of my abandoned projects. (can be reproduced in 1.04)

Also, doesn't 'cln' mean 'clean'? I think 'seq' does what 'cln' should (not sure).

Module:
https://disk.yandex.ru/d/8nfnO_smpmvN7Q

**Comment by SyntaxErrol** [comment]
"Cln" means clone. It clones the current pattern to the next unused pattern number and inserts that into the sequence. "Seq" only does the latter.

**Comment by coderofsalvation** [comment]
I've been testing this with a debug build, and added a printf at `ModuleEditor::seqCurrentOrderPosition`:

```cpp
  if (clone)
  {   
    // now clone pattern       
    printf("dest %i src %i\n",(int)dstPatternIndex,(int)srcPatternIndex);
    module->phead[dstPatternIndex] = module->phead[srcPatternIndex];                                                                                                                          
  }
```

gdb gives this backtrace

```
dest 256 src 160

Thread 1 "milkytracker" received signal SIGSEGV, Segmentation fault.
0x00007ffff76b232e in free () from /nix/store/j0by58xwyc66f884x0q8rpzvgpwvjmf2-glibc-2.38-77/lib/libc.so.6
(gdb) bt
#0  0x00007ffff76b232e in free () from /nix/store/j0by58xwyc66f884x0q8rpzvgpwvjmf2-glibc-2.38-77/lib/libc.so.6
#1  0x00000000004f72dd in TXMPattern::operator= (this=0x751740, src=...) at /home/leon/projects/MilkyTracker/src/milkyplay/XModule.cpp:1179
#2  0x00000000004266d7 in ModuleEditor::seqCurrentOrderPosition (this=this@entry=0x6e7eb0, index=<optimized out>, clone=clone@entry=true)
    at /home/leon/projects/MilkyTracker/src/tracker/ModuleEditor.cpp:933
#3  0x00000000004a1818 in Tracker::handleEvent (this=0x723740, sender=0x118c9b0, event=<optimized out>) at /home/leon/projects/MilkyTracker/src/tracker/Tracker.cpp:1007
#4  0x000000000051c021 in PPButton::handleButtonRelease (this=0x118c9b0, event=0x7fffffff6960, postEvent=eCommand, rMouseDown=<optimized out>, lMouseDown=<optimized out>)
    at /home/leon/projects/MilkyTracker/src/ppui/Button.cpp:309
#5  0x000000000051d0a9 in PPButton::dispatchEvent (this=0x118c9b0, event=0x7fffffff6960) at /home/leon/projects/MilkyTracker/src/ppui/Button.cpp:233
#6  0x000000000051e654 in PPContainer::dispatchEvent (this=0x118c5b0, event=0x7fffffff6960) at /home/leon/projects/MilkyTracker/src/ppui/Container.cpp:116
#7  0x000000000051e654 in PPContainer::dispatchEvent (this=0xd00e80, event=0x7fffffff6960) at /home/leon/projects/MilkyTracker/src/ppui/Container.cpp:116
#8  0x00000000004bef80 in RaiseEventSerialized (event=0x7fffffff6960) at /home/leon/projects/MilkyTracker/src/tracker/sdl/SDL_Main.cpp:152
#9  RaiseEventSerialized (event=0x7fffffff6960) at /home/leon/projects/MilkyTracker/src/tracker/sdl/SDL_Main.cpp:147
#10 translateMouseUpEvent (mouseButton=<optimized out>, localMouseX=<optimized out>, localMouseY=<optimized out>) at /home/leon/projects/MilkyTracker/src/tracker/sdl/SDL_Main.cpp:432
#11 0x0000000000412a68 in main (argc=<optimized out>, argv=<optimized out>) at /home/leon/projects/MilkyTracker/src/tracker/sdl/SDL_Main.cpp:1050
```

I was hoping somebody with c++/operator-overloading experience could figure this one out
